export const SETTING_KEYS = [
  "site_name",
  "site_tagline",
  "site_description",
  "logo_image_url",
  "logo_dark_url",
  "favicon_url",
  "logo_text_line1",
  "logo_text_line2",
  "hero_title",
  "hero_title_accent",
  "hero_subtitle",
  "hero_bg_image",
  "hero_cta_text",
  "hero_cta_url",
  "cta_bg_image",
  "cta_eyebrow",
  "cta_title",
  "cta_title_accent",
  "cta_cta_label",
  "footer_tagline",
  "footer_copyright",
  "footer_facebook",
  "footer_instagram",
  "footer_youtube",
  "contact_phone",
  "contact_email",
  "contact_address",
] as const;

export type SettingKey = (typeof SETTING_KEYS)[number];

export const SETTING_DEFAULTS: Record<SettingKey, string> = {
  site_name: "Malnad Realty Guide",
  site_tagline: "Know the place before you buy",
  site_description: "Property, land, homes and local insights across Shimoga & Uttarakannada District.",
  logo_image_url: "",
  logo_dark_url: "",
  favicon_url: "",
  logo_text_line1: "MALNAD REALTY",
  logo_text_line2: "GUIDE",
  hero_title: "Know the place",
  hero_title_accent: "before you buy.",
  hero_subtitle: "Property, land, homes and local insights across Shimoga & Uttarakannada District.",
  hero_bg_image: "/hero-bg.jpg",
  hero_cta_text: "Explore Locations",
  hero_cta_url: "/locations",
  cta_bg_image: "",
  cta_eyebrow: "Looking for a property?",
  cta_title: "Explore verified properties on",
  cta_title_accent: "Malnad Realty",
  cta_cta_label: "Visit Malnad Realty",
  footer_tagline:
    "Know the place before you buy. Property, land, homes and local insights across Shimoga & Uttarakannada District.",
  footer_copyright: "Malnad Realty",
  footer_facebook: "",
  footer_instagram: "",
  footer_youtube: "",
  contact_phone: "",
  contact_email: "",
  contact_address: "",
};
